### ISSUE TITLE
Timer Issue - Conflict between Classic Theme and Quiz Setting in v3.5 & v3.6

### ISSUE THREAD

**Issue by amberborr** [bmbrands/moodle-theme_classic#4]
When using Classic theme, in the quiz settings under the extra restrictions on attempts, if you set the browser security drop down to full screen pop-up with some JavaScript security, the timer doesn't display during the quiz.

If you set the browser security drop down to none, it works fine.

Only happens using Classic Theme.
It seems to be a conflict with the Classic theme and the quiz setting.

To reproduce

Access a course using the Classic Theme

Under Course Administration click Turn Editing on
Click on Add Activity or Resource
Click Quiz, then Add
Name your quiz
Under Timing set enable Time Limit and set to whatever time
Under Extra restrictions on attempts click Show more....
Set Browser security to Full screen pop-up with some JavaScript security
Click Save and Display
Edit quiz to manually add a question
For the sake of this scenario, select True or False
Fill in mandatory sections
Click Save changes when done
Click preview, then start attempt
Timer does not display on the Quiz Navigation block
Click on Edit Settings under Quiz Administration
Set the browser security to none
Click Save and Display
Click preview, then start attempt
Timer displays in Quiz Navigation Block

**Comment by bmbrands** [comment]
Hi @amberborr 

Thanks for reporting this issue. The classic theme is not maintained here but on the Moodle tracker since it is now part of Moodle core.

Could you post your issue on tracker.moodle.org?

Thanks!

**Comment by amberborr** [comment]
Hi @bmbrands ,
I originally reported it in tracker.moodle.org; https://tracker.moodle.org/browse/MDL-66548?filter=-2 however I was advised to report it here. 

Thank you

Amber

**Comment by bmbrands** [comment]
Ah I see! So the issue has been resolved for newer versions of Moodle. Is it an option to update your version?

**Comment by amberborr** [comment]
Not at this time as we are Blackboard Open LMS, so we are just on v3.6. Just was putting it out there as a known issue when using this theme plugin on v3.5 and v3.6.

**Comment by bmbrands** [comment]
Thanks for the info. I have added a patch to MDL-66548 on the moodle tracker and updated the Moodle 3.6 branch here on this repo.
I have removed the v3.5 branch as I will not be supporting it.
